services:
  # 1. Reverse Proxy (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - n8n_app
      - code_server
    networks:
      - app-network

  # 2. Frontend (Vite)
  frontend:
    build: ./frontend
    #container_name: vite_frontend
    # Nginx가 내부에서 접근하므로 외부 포트 5173:5173은 없어도 되지만, 
    # 로컬 테스트를 위해 유지해도 무방합니다.
    ports:
      - "5173:5173" # 왼쪽(호스트) 포트가 터널이 바라보는 포트와 같아야 합니다.
    networks:
      - app-network

  # 3. Backend (Node.js)
  backend:
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - REDIS_PORT=6379
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  # 4. n8n (n8n.memyself.shop)
  n8n_app:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=n8n.memyself.shop
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL}  # 웹훅 주소에서 포트 제거
      - NODE_ENV=production
    ports:
      - "5678:5678"
    networks:
      - app-network

  # 5. Code Server (code.memyself.shop)
  code_server:
    image: linuxserver/code-server
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
      - PASSWORD=${CODE_SERVER_SECRET} # 접속 비밀번호 설정  ##
    ports:
      - "8080:8443"
    volumes:
      - /home:/config/workspace
      - /home/linux_server/.gitconfig:/config/.gitconfig
      - /home/user/code-server/config:/config
    networks:
      - app-network

  # 6. Database (MySQL)
  db:
    image: mysql:8.0
    #container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: trip-db
      MYSQL_ROOT_PASSWORD: 1234 ##
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  # 7. Cache (Redis)
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
